### ISSUE TITLE
Ticcutils (and possible others) break with ICU 61 due to missing namespace

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/ticcutils#14]
Today I noticed ticcutils fails to build on Mac OS X (fbkarsdorp/homebrew-lamachine#10), the cause is a libicu upgrade by homebrew and ticcutils not being ready for it. See https://ssl.icu-project.org/repos/icu/trunk/icu4c/readme.html#RecBuild for a solution.

New releases will be needed as this completely breaks the LaMachine stable release on Mac OS X. :(   (which I just release an hour ago ;) )

Surprisingly homebrew is ahead of Arch Linux here, I'm still on 60.2 locally, but it will soon also fail on linux..

**Comment by proycon** [comment]
For the time being I implemented a workaround in LaMachine (https://github.com/proycon/LaMachine/issues/69) and the homebrew packages to trigger the old behaviour ( ``-DU_USING_ICU_NAMESPACE=1``), so the urgency is less now.

**Comment by kosloot** [comment]
I did some effort to add icu namespaces in all C++ software
I would be pleased with feedback on modules still failing when -DU_USING_ICU_NAMESPACE=1 is NOT set.

**Comment by kosloot** [comment]
assume this is ok now
