### ISSUE TITLE
error: Could not find a version of the Boost::Regex library!

### ISSUE THREAD

**Issue by yurivict** [LanguageMachines/ticcutils#18]
The relevant portion of config.log:
```
configure:17543: checking whether the Boost::Regex library is available
configure:17566: c++ -c -O2 -pipe -fno-omit-frame-pointer -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include  -fopenmp -pthread -fno-omit-frame-pointer -isystem /usr/local/include -I/usr/local/include -I/usr/local/include conftest.cpp >&5
conftest.cpp:59:15: warning: empty parentheses interpreted as a function declaration [-Wvexing-parse]
boost::regex r(); return 0;
              ^~
conftest.cpp:59:15: note: remove parentheses to declare a variable
boost::regex r(); return 0;
              ^~
1 warning generated.
configure:17566: $? = 0
configure:17580: result: yes
configure:17728: error: Could not find a version of the Boost::Regex library!
```

Please note that there are no error messages, only warnings.

boost-libs-1.68.0_2 is installed.
FreeBSD 11.2 amd64

**Comment by yurivict** [comment]
In short: the first problem is that your detection script fails without saying what went wrong.

**Comment by yurivict** [comment]
FYI: autoconf-archive-0.2017.09.28 installs /usr/local/share/aclocal/ax_boost_regex.m4 that can detect boost::Regex. You might want to just use it instead.

**Comment by kosloot** [comment]
I am a bit confused, as the ax_boost_regex.m4 we provide looks exactly the autoconf-archive-0.2017.09.28 version. What differences do you see?
We provide our own version as in the past the ax_boost macro's didn't work on all setups we tried. Relying on the OS provided version would be preferable but in fact this one is flawed too:

It has the offending line: ``boost::regex r(); return 0;``
On my system (Ubuntu 18.10) Clang++-7 emits the warning, but he configuration completes and boost::regex works. Unfortunately GCC just accepts the line without any notice.
I is unclear to me why in your setup this is different and the ``Could not find a version of the Boost::Regex library!`` line is produced (as ``result:yes`` is output just before)

Anyway: I could change the .m4 script to make it work, but this is second best. Better would be to know what the scrips look like on BSD and why it fails there and not on Ubuntu.

**Comment by yurivict** [comment]
Maybe this is a bug in ax_boost_regex.m4 autoconf-archive, but it fails without saying why.

**Comment by yurivict** [comment]
Removing braces doesn't help, the warnings are a separate issue.
I don't have OpenBSD.

**Comment by yurivict** [comment]
I use github.
The workaround is to add ```XXFLAGS+=-DHAVE_BOOST_REGEX``` and ```LDFLAGS+=-lboost_regex```.

**Comment by kosloot** [comment]
Ok, then. I meant FreeBSD of course.
I was under the impression that the failure was due to the Warning. As suggested by the original report.
If not, it is even spookier. 
As I don't have access to a FreeBSD system, sorting this out is not really an option for me.
First question always being: Is it a problem on ANY FreeBSD system, or just on some configurations?

**Comment by yurivict** [comment]
This is the problem on any FreeBSD system. But if these ```ax_boost_regex.m4``` files are identical with autoconf, then this isn't your problem. Having the workaround, the FreeBSD port works fine with it too.

Reporting this to GNU tools IMO is useless, it will end up in the mailing list.

**Comment by yurivict** [comment]
Please feel free to close if you wish.

**Comment by kosloot** [comment]
Well a bit unsatisfying, but glad that you found a workaround.
Thanks for using, and commenting on, our software anyway!

**Comment by kosloot** [comment]
@yurivict  FYI:
Skimming old issues, I stumbled upon this one. 
The dependency on Boost is long gone for all our software.

**Comment by yurivict** [comment]
@kosloot 
Thanks for this info.
I removed the boost dependency from the port.
