### ISSUE TITLE
Test failures when disabling Boost Regex

### ISSUE THREAD

**Issue by egpbos** [LanguageMachines/ticcutils#19]
When building on Linux without Boost Regex, i.e. with `./configure --with-boost=no`, I get 6 failing tests:

```sh
test: test_tar(545):   FAILED  
test_tar(545) : '0' != '3'

[...]

test: test_fileutils(568):   FAILED  
test_fileutils(568) : '0' != '1'
test: test_fileutils(569):  OK  
test: test_fileutils(571):   FAILED  
test_fileutils(571) : '0' != '2'
test: test_fileutils(572):  OK  
test: test_fileutils(574):   FAILED  
test_fileutils(574) : '0' != '1'
test: test_fileutils(575):   FAILED  
test_fileutils(575) error: 'TiCC::searchFilesMatch: invalid regexp: regex_error'
test: test_fileutils(577):   FAILED  
test_fileutils(577) : '0' != '2'
```

These are the following tests in [runtest.cxx](https://github.com/LanguageMachines/ticcutils/blob/master/src/runtest.cxx):

```c++
  assertNoThrow( mytar.extract_file_names_match( res, "s*b" ) ); // NOT THIS ONE
  assertEqual( res.size(), 3 );     // FAILS

// [...]

  assertNoThrow( res = searchFilesMatch( path, "*.txt", false ) );
  // non recursive. should match small.txt
  assertEqual( res.size(), 1 );     // FAILS
  assertNoThrow( res = searchFilesMatch( path, "*.txt" ) );
  // recursive should match small.txt and sub1/sub.txt
  assertEqual( res.size(), 2 );     // FAILS
  assertNoThrow( res = searchFilesMatch( path, "small" ) );
  // should match small.txt
  assertEqual( res.size(), 1 );     // FAILS
  assertNoThrow( res = searchFilesMatch( path, "s*[lb].txt" ) );     // ALSO FAILS
  // should match small.txt and sub1/sub.txt
  assertEqual( res.size(), 2 );     // FAILS
```

All these functions call `wildToRegExp` to create a compatible pattern and then do a `regex_search` on the pattern. Apparently, this turns up zero results on all searches and in the last case even throws due to an invalid pattern.

This problem exists only in very specific circumstances, which may help pinpoint the exact problem:
- The problem only shows on Linux, not in macOS builds
- The problem exists in non-Boost builds in version 0.20 see https://github.com/LanguageMachines/ticcutils/compare/master...TICCLAT:check_without_boost_0.20 and https://travis-ci.org/TICCLAT/ticcutils/jobs/467574569
- In master (at least after commit d004762)
  + ... on Travis it builds and tests fine without Boost: https://travis-ci.org/TICCLAT/ticcutils/builds/467544848
  + ... but in a (conda-forge) build on CircleCI it again shows the same issues as 0.20: https://circleci.com/gh/egpbos/staged-recipes/1

The fact that d004762 (which updates the m4 Boost scripts!) fixes things on Travis compared to 0.20 may be an important clue. However, I'm not at all familiar with autotools, so I don't see how this could make a difference in the CircleCI/conda case. The way I understand it is that these m4 scripts are copied from the TICC Utils repo itself, so this should happen in CircleCI as well, I'd say.

**Comment by egpbos** [comment]
Actually, when not using Boost, the addition of the m4 Boost scripts should not matter, right?

It seems like the only possibly influential difference between master and v0.20 is then that the Travis build switched from Trusty to Xenial, see diff: https://github.com/LanguageMachines/ticcutils/compare/v0.20...LanguageMachines:master

This will surely lead to version differences, which may also very well explain the difference with the CircleCI/Conda build. The CircleCI build may be using similar dependencies as the 0.20/Trusty build, whereas it should perhaps be using Xenial dependencies.

**Comment by egpbos** [comment]
Oh, and there's also the OSX m4 script that was added, maybe that plays a role as well...

**Comment by egpbos** [comment]
Indeed, the CircleCI build is on Trusty.

**Comment by egpbos** [comment]
Ok, so indeed Trusty vs Xenial seems to trigger the test failures. I set back the Travis environment for the master build back to Trusty and now it also fails the Linux build, just like v0.20: https://travis-ci.org/TICCLAT/ticcutils/builds/477259808

Now to figure out what exactly is the issue in Trusty vs Xenial...

**Comment by kosloot** [comment]
Well, one issue is:
Trusty comes with gcc4.8 which is the whole reason to use boost_regex in the first place, because gcc4.8 doesn't implement C++11 regexps correctly.
xenial provides a decent C++11 implementation, which makes boost 'obsolete'

**Comment by egpbos** [comment]
Indeed, this seems to be the problem! Configure seems to detect and use `g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)` for the conda build. It should in fact detect the Conda installed GCC 7.2 compilers, so I'll have to look into how to get that to work.

**Comment by egpbos** [comment]
Ok, my Conda build is now working, it turned out I hadn't actually installed GCC 7.2 :) Now I have and everything works. See https://github.com/conda-forge/staged-recipes/pull/7246

Thanks @kosloot!
