### ISSUE TITLE
Error with ./configure on OS X 10.11.3

### ISSUE THREAD

**Issue by evanmiltenburg** [LanguageMachines/ticcutils#2]
I got the following error messages:

```
./configure: line 16586: syntax error near unexpected token `,AC_MSG_ERROR'
./configure: line 16586: `ACX_PTHREAD(,AC_MSG_ERROR([We need pthread support!]))'
```

**Comment by evanmiltenburg** [comment]
The bootstrapping process also wasn't perfect. After using `bash bootstrap.sh`:

    aclocal: installing 'm4/libtool.m4' from '/opt/local/share/aclocal/libtool.m4'
    aclocal: installing 'm4/ltoptions.m4' from '/opt/local/share/aclocal/ltoptions.m4'
    aclocal: installing 'm4/ltsugar.m4' from '/opt/local/share/aclocal/ltsugar.m4'
    aclocal: installing 'm4/ltversion.m4' from '/opt/local/share/aclocal/ltversion.m4'
    aclocal: installing 'm4/lt~obsolete.m4' from '/opt/local/share/aclocal/lt~obsolete.m4'
    aclocal: installing 'm4/pkg.m4' from '/opt/local/share/aclocal/pkg.m4'
    glibtoolize: putting auxiliary files in '.'.
    glibtoolize: linking file './ltmain.sh'
    configure.ac:68: error: possibly undefined macro: AC_MSG_ERROR
          If this token and others are legitimate, please use m4_pattern_allow.
          See the Autoconf documentation.
    autoreconf: /opt/local/bin/autoconf failed with exit status: 1

But it did complete after using `sudo bash bootstrap.sh`:

    configure.ac:25: installing './compile'
    configure.ac:25: installing './config.guess'
    configure.ac:25: installing './config.sub'
    configure.ac:8: installing './install-sh'
    configure.ac:8: installing './missing'
    src/Makefile.am: installing './depcomp'
    parallel-tests: installing './test-driver'

**Comment by proycon** [comment]
This error is most likely due to a missing package on your system: ``autoconf-archive``, you can install it through homebrew for instance.

You can also try our LaMachine distribution (https://proycon.github.io/LaMachine), which contains scripts to compile and install ticcutils and most of our other software.

**Comment by evanmiltenburg** [comment]
Thanks, but after (successfully) installing autoconf-archive with `brew install autoconf-archive`, it gives the same error.

**Comment by proycon** [comment]
Sorry for the delay!  Mac can often be rather confusing as there tend to be multiple different versions of things and it doesn't always follow proper standards. Is your ``autoconf`` also installed through homebrew? I'm guessing this version of ``autoconf`` probably can't find the ``autoconf-archive``.

LaMachine installs the following dependencies through homebrew to compile and install most of our software, if you have other conflicted versions around things may break:
 ``brew install pkg-config autoconf automake libtool autoconf-archive boost --with-python  boost-python xml2 libxslt icu4c``

**Comment by kosloot** [comment]
Closing this. Some OSX issues have been solved the last year, and we didn't get any feedback from @evanmiltenburg unfortunately.
