### ISSUE TITLE
move json.hpp to ticcutils

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/ticcutils#20]
Currently json.hpp is installed by our own autoconfiguratable fork of nlohmann/json, which although although I see the reasoning introduces a big problem for distribution as it introduces another dependency to maintain, and one which is not really ours (so keeping in sync with upstream is another issue). This becomes especially problematic when considering this would imply a new debian, homebrew, and AUR package (not to mention the work of third parties on BSD or Fedora). 

As this json library is set up as a single header file (which they seem to have done especially to avoid dependency problems), the easiest solution would be to just adopt it in ticcutils as ``include/ticcutils/json.hpp``.

**Comment by kosloot** [comment]
yeah, this may save is some trouble.
The single include json.hpp is now a file in include/ticcutils

**Comment by kosloot** [comment]
Seems to work as expected.
