### ISSUE TITLE
installation issue in centos with latest version

### ISSUE THREAD

**Issue by padurucr7** [LanguageMachines/ticcutils#23]
Getting below error for v0.24 , however v0.23 is working fine

XMLtools.cxx: In function ‘std::list<_xmlNode*> TiCC::FindNodes(const xmlDoc*, const string&)’:
XMLtools.cxx:270:53: error: invalid conversion from ‘const xmlDoc* {aka const _xmlDoc*}’ to ‘xmlDocPtr {aka _xmlDoc*}’ [-fpermissive]
     const xmlNode *root = xmlDocGetRootElement( doc );
                                                     ^
XMLtools.cxx: In function ‘xmlNode* TiCC::xPath(const xmlDoc*, const string&)’:
XMLtools.cxx:298:53: error: invalid conversion from ‘const xmlDoc* {aka const _xmlDoc*}’ to ‘xmlDocPtr {aka _xmlDoc*}’ [-fpermissive]
     const xmlNode *root = xmlDocGetRootElement( doc );
                                                     ^
make[2]: *** [XMLtools.lo] Error 1

**Comment by padurucr7** [comment]
XMLtools.cxx: In function ‘std::list<_xmlNode*> TiCC::FindNodes(const xmlDoc*, const string&)’:
XMLtools.cxx:270:53: error: invalid conversion from ‘const xmlDoc* {aka const _xmlDoc*}’ to ‘xmlDocPtr {aka _xmlDoc*}’ [-fpermissive]
     const xmlNode *root = xmlDocGetRootElement( doc );
                                                     ^
XMLtools.cxx: In function ‘xmlNode* TiCC::xPath(const xmlDoc*, const string&)’:
XMLtools.cxx:298:53: error: invalid conversion from ‘const xmlDoc* {aka const _xmlDoc*}’ to ‘xmlDocPtr {aka _xmlDoc*}’ [-fpermissive]
     const xmlNode *root = xmlDocGetRootElement( doc );
                                                     ^
make[2]: *** [XMLtools.lo] Error 1

**Comment by proycon** [comment]
I'm investigating what could be the cause of this, as it does seem to compile properly on other systems. Is this CentOS 8 you are running on? On CentOS 7 I imagine there could be issues with outdated dependencies.

**Comment by padurucr7** [comment]
yeah its happening in centos 7 . I tried this now  in amzon linux2 instance and getting the same issue

**Comment by proycon** [comment]
Ok, Amazon Linux 2 is also based on CentOS 7, so that explains it. Is upgrading to CentOS 8 an option for you? (although I must warn that there are also issues there, such as [a missing libtar-devel package](https://bugs.centos.org/view.php?id=17330), the remedy for that one is to compile and install libtar from source yourself, which is also what our [LaMachine](https://proycon.github.io/lamachine) meta-distribution does.

I'll see if it is still possible to make the current code compatible so it compiles on CentOS 7 too.

**Comment by padurucr7** [comment]
No , currently we cannot upgrade to  8  :/

**Comment by proycon** [comment]
The above commit should fix the issue. I'm still awaiting the integration test results of the full software stack to see if this doesn't lead to problems elsewhere.

We officially deprecated CentOS 7 as most of its packages (including the gcc compiler) are becoming too old, so I can't guarantee that there won't be further issues in compiling the latest libfolia, ucto and frog on CentOS 7, but we'll have to see. (earlier versions of our software stack will work though).

**Comment by proycon** [comment]
The tests succeeded. Can you give it a try with the latest git master version?

**Comment by padurucr7** [comment]
thanks Maarten , its working now .
