### ISSUE TITLE
libtar causes issues accross distros

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/ticcutils#25]
I keep running into issues around libtar on various Linux distributions. It's seemingly not as common a library as you'd expect.

* The original page http://www.feep.net/libtar/ is offline, a fork https://repo.or.cz/libtar.git seems unmaintained since 2013, another fork https://github.com/tklauser/libtar has some updates but is also 'archived' while having seemingly important open pull requests to make it work with modern compilers.
* The libtar headers packaged on CentOS 7 are not compatible with ticcutils (const char * vs char * mismatch in `tar_open()`)
* CentOS 8 hasn't packaged libtar-devel at all (it does have libtar though), I had to resort to stealing a dev package from a binary-compatible distro that did package it. It used to work, but now I am running into another issue there again: https://github.com/proycon/python-ucto/actions/runs/3949694434/jobs/6761235259#step:5:1123
* Alpine Linux didn't have a package for libtar at all, now it does because I packaged it myself.

It's causing a bit too much of a headache, so I wonder if we can't just make libtar optional (``./configure --disable-libtar``?) in ticcutils (and all our software stack that builds on it.. many people can live without the tar.gz and tar.bz2 support some of our libraries offer), or find an alternative for it that's better maintained.

**Comment by proycon** [comment]
I actually managed to get around one of the errors (the ``::malloc`` one from point 3) while building on CentOS 7. Setting an explicit ``$LD_LIBRARY_PATH`` helped there (a lot of stuff was in a non-standard location). So at least the latest version of libtar works.

This has lower priority now.

**Comment by kosloot** [comment]
OK:
libtar seems not to be maintained for a long time now. Indeed the git repository is [archived](https://ubuntu.com/about/release-cycle)

We might search for a replacement in  the future, or make the build optional indeed. Which is quite a hassle

BUT! GOOD News!
ticcutils seems to be the only package in our software stack that actively uses libtar (to test the working)
so removing it completely should be possible, and is the best solution.

I will have to triple-check this of course

**Comment by kosloot** [comment]
I removed Tar.cxx and Tar.h from ticcutils.
I also removed all dependencies on libtar from the packages that I manage
