### ISSUE TITLE
Consider moving away from unmaintained library libtar

### ISSUE THREAD

**Issue by diizzyy** [LanguageMachines/ticcutils#27]
It's been unmaintained for multiple years and is also plauged with several CVEs, see https://www.opencve.io/cve?vendor=feep&product=libtar

**Comment by kosloot** [comment]
We don't depend on libtar anymore since commit d2b3d7f581d1940a5fb422c2496184500b9e7504
Which is included in release https://github.com/LanguageMachines/ticcutils/releases/tag/v0.31 and above

**Comment by diizzyy** [comment]
Thanks, I've create a PR to remove it from README.md
