### ISSUE TITLE
please ship new .tar.gz release

### ISSUE THREAD

**Issue by joostvb-gh** [LanguageMachines/ticcutils#3]
Hi,

I'd like to upload a new ticcutils to the Debian apt archive.  Latest release makes this hard.  The
automake commit I've made fixes the build in Debian. Could a new ticcutils .tar.gz get shipped
with that commit included?

Thanks, Bye, Joost

**Comment by proycon** [comment]
Done: https://github.com/LanguageMachines/ticcutils/releases/tag/v0.13.1

**Comment by joostvb-gh** [comment]
On Tue, Jul 26, 2016 at 05:07:44AM -0700, Maarten van Gompel wrote:
> Done: https://github.com/LanguageMachines/ticcutils/releases/tag/v0.13.1

Great, will package and upload to Debian either tonight or within a week.

Bye,

Joost
