### ISSUE TITLE
Package requirements (libxml-2.0 >= 2.6.16 )

### ISSUE THREAD

**Issue by vivekpatani** [LanguageMachines/ticcutils#6]
```
 flipswitch@devcenter  ~/junkyard/ticcutils   master ?  sudo apt-get install libxml2-dev   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxml2-dev is already the newest version (2.9.3+dfsg1-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.

 flipswitch@devcenter  ~/junkyard/ticcutils   master ?  bash bootstrap.sh

flipswitch@devcenter  ~/junkyard/ticcutils   master ?  ./configure
...
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
./configure: line 17691: test: : unary operator expected
checking for boostlib >= 1.50... yes
checking whether the Boost::Regex library is available... yes
checking for exit in -lboost_regex... yes
checking for pkg-config... /home/flipswitch/.linuxbrew/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for XML2... no
configure: error: Package requirements (libxml-2.0 >= 2.6.16 ) were not met:

No package 'libxml-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables XML2_CFLAGS
and XML2_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

Would really appreciate some help. I went through a few answers but none of them could answer.

**Comment by proycon** [comment]
I think there may be something strange going on with your pkg-config? It is detecting pkg-config in a custom location (``/home/flipswitch/.linuxbrew/bin/pkg-config``) rather than the global ``/usr/bin/pkg-config``, and it looks like this one doesn't access the globally installed packages. Perhaps remove ``.linuxbrew/bin`` from your ``$PATH`` and try again?

By the way, for installing most of our software (including ticcutils), our LaMachine distribution is usually the easiest solution: https://proycon.github.io/LaMachine

**Comment by vivekpatani** [comment]
Genius! That worked. Can you please explain briefly what was happening?

**Comment by vivekpatani** [comment]
```
/home/flipswitch/lamachine/lib/libticcutils.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/home/flipswitch/lamachine/lib/libticcutils.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
//usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
make[2]: *** [folialint] Error 1
Makefile:682: recipe for target 'folialint' failed
make[2]: Leaving directory '/home/flipswitch/lamachine/src/libfolia/src'
make[1]: *** [all-recursive] Error 1
Makefile:477: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/home/flipswitch/lamachine/src/libfolia'
Makefile:386: recipe for target 'all' failed
make: *** [all] Error 2
================ FATAL ERROR ==============
An error occurred during installation!!
libfolia make failed
===========================================
```

Now stuck with this error.

**Comment by proycon** [comment]
What was happening before is that it found a custom version of pkg-config rather than the globally installed version, and that version didn't know about libxml2. pkg-config is used to find the library/include flags for the compiler.

**Comment by proycon** [comment]
I'm not sure about that new error yet, I think @kosloot is looking into that?

**Comment by kosloot** [comment]
I am not quite sure what happened here.
But at the moment, the GIT versions are a bit unstable after an attempt to remove boost dependencies. At least you could try to update ticcutils and then libfolia. 
But we will revert the change shortly, to maintain compatibility with old 4.8 gcc versions

In general it is a good idea to install only official releases of our packages.
You find those at the 'releases' tab of https://github.com/LanguageMachines/ticcutils etc.
(but even then a local pkg-config might run havoc)

Alternatively use LaMachine, and get everything for free:
see https://github.com/proycon/LaMachine

**Comment by kosloot** [comment]
I Just realized that you are already using LaMachine.
So there is some other problem. i hope @proycon can enlighten us...

**Comment by proycon** [comment]
Is this issue still unresolved? If so, try a ``lamachine-update.sh force`` (or a fresh LaMachine install), because I still don't know what causes this nor can I reproduce it.

**Comment by kosloot** [comment]
closed due to lack of response.
