### ISSUE TITLE
Unable to compile in Ubuntu Server 16.04 LTS

### ISSUE THREAD

**Issue by limogin** [LanguageMachines/ticcutils#7]
I see this error messge when try to call 

$ ./configure 
[...]
checking for g++ option to support OpenMP... -fopenmp
./configure: line 16099: syntax error near unexpected token `,'
./configure: line 16099: `AX_CHECK_ZLIB( ,'

**Comment by kosloot** [comment]
It looks like you don't have the autoconf-archive installed.
Please install this:
sudo apt install autoconf-archive

**Comment by proycon** [comment]
You might also want to look into LaMachine (https://proycon.github.io/LaMachine), which can compile ticcutils and our other software for you.
