### ISSUE TITLE
revise dependency on Boost Regex 

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/ticcutils#9]
The package needs libboost-regex-dev to completely build.
This requirement is only there for old gcc4.8 compilers with limited regexp support.
Without regexp the package builds, but some functionality is limited then. This surpises other packages that rely on these functions.

Solution1:
- refuse to build without boost-regex

Solution 2:
- build, an use C++ regexp functionality when gcc > 4.9
- don't build otherwise

Solution 2 seems best. But is it possible to check for compiler versions on the configuration step?
Otherwise you would need to conditionally compile and force a compiler error when the version is too old and boost isn't available.

**Comment by proycon** [comment]
This seems to cause some problems on CentOS 7 (gcc 4.8, they're rather conservative) when there is no global boost available but when I compiled a manual boost installation and installed it in a non-default location (i.e. in the LaMachine user environment):

```
checking for boostlib >= 1.50... configure: We could not detect the boost libraries (version 1.50 or higher). If you have a staged boost library (still not installed) please specify $BOOST_ROOT in your environment and do not give a PATH to --with-boost op
tion.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.
configure: error: No Regular expression support available. Please install libboost-regex-dev
```

Passing ``--with-boost``,``--with-boost-libdir`` or setting ``$BOOST_ROOT`` all has no effect.

**Comment by kosloot** [comment]
The Boost dependency has been removed. 
Sorry for those living in Medieval times.
